server:
    port: 8080

spring:
  profiles:
    active: dev
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring_boot_test
    username: postgres
    password: root
    maximumPoolSize: 10